#!/usr/bin/env bash
# @decision: Terminal setup in 6 phases: CLI tools, oh-my-zsh, Starship, .zshrc write,
# fzf key bindings, macOS defaults. Starship chosen over Powerlevel10k because it works
# without an interactive wizard and is cross-shell. oh-my-zsh coexists: ZSH_THEME=""
# disables its prompt so Starship takes over. zsh-autosuggestions and zsh-syntax-highlighting
# installed via brew (not OMZ custom plugins) to avoid git-clone network issues.

CLI_TOOLS=(
    git
    gh
    curl
    wget
    nvm
    starship
    zsh-autosuggestions
    zsh-syntax-highlighting
    fzf
    bat
    eza
    ripgrep
    fd
    jq
    tldr
    htop
    tree
    git-delta
)

setup_terminal() {
    section_header "Setting Up Your Terminal"

    _install_cli_tools
    _install_nerd_font
    _install_ohmyzsh
    _configure_starship
    _write_zshrc
    _configure_fzf
    _configure_mac_defaults
}

_install_cli_tools() {
    step "Installing CLI developer tools..."
    # brew install is idempotent — skips already-installed formulas automatically
    brew install "${CLI_TOOLS[@]}" 2>&1 | tee -a "${MACBEQUICK_LOG}"
    ok "CLI tools installed"
}

_install_nerd_font() {
    step "Installing MesloLGM Nerd Font (needed for terminal icons)..."
    if brew list --cask font-meslo-lg-nerd-font &>/dev/null 2>&1; then
        skip "MesloLGM Nerd Font already installed"
        return 0
    fi
    brew install --cask font-meslo-lg-nerd-font 2>&1 | tee -a "${MACBEQUICK_LOG}"
    ok "Nerd Font installed"
}

_install_ohmyzsh() {
    step "Installing oh-my-zsh..."
    if [[ -d "${HOME}/.oh-my-zsh" ]]; then
        skip "oh-my-zsh already installed"
        return 0
    fi
    # --keep-zshrc: don't overwrite existing .zshrc; we write ours in _write_zshrc
    # --unattended: skip interactive prompts and the chsh call
    RUNZSH=no CHSH=no sh -c \
        "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" \
        "" --unattended --keep-zshrc \
        2>&1 | tee -a "${MACBEQUICK_LOG}"
    ok "oh-my-zsh installed"
}

_configure_starship() {
    step "Configuring Starship prompt..."
    mkdir -p "${HOME}/.config"
    if [[ -f "${HOME}/.config/starship.toml" ]]; then
        skip "Starship config already exists"
        return 0
    fi
    starship preset pastel-powerline -o "${HOME}/.config/starship.toml" 2>&1 | tee -a "${MACBEQUICK_LOG}"
    ok "Starship configured with pastel-powerline preset"
}

_write_zshrc() {
    step "Writing ~/.zshrc..."

    local marker="# Generated by macbequick"
    if grep -q "${marker}" "${HOME}/.zshrc" 2>/dev/null; then
        skip "~/.zshrc already written by macbequick"
        return 0
    fi

    # Back up existing .zshrc if present
    if [[ -f "${HOME}/.zshrc" ]]; then
        local backup="${HOME}/.zshrc.macbequick-backup-$(date +%Y%m%d%H%M%S)"
        cp "${HOME}/.zshrc" "${backup}"
        step "Backed up existing ~/.zshrc to ${backup}"
    fi

    cp "${SCRIPT_DIR}/config/zshrc.template" "${HOME}/.zshrc"
    ok "~/.zshrc written"
}

_configure_fzf() {
    step "Setting up fzf key bindings (CTRL+R history search, CTRL+T file picker)..."
    "$(brew --prefix fzf)/install" \
        --key-bindings --completion --no-update-rc --no-bash --no-fish \
        2>&1 | tee -a "${MACBEQUICK_LOG}" || true
    ok "fzf key bindings configured"
}

_configure_mac_defaults() {
    step "Applying developer-friendly macOS defaults..."

    # Show hidden files and extensions in Finder
    defaults write com.apple.finder AppleShowAllFiles -bool true
    defaults write NSGlobalDomain AppleShowAllExtensions -bool true

    # Finder path bar + status bar (shows where you are and how many items)
    defaults write com.apple.finder ShowPathbar -bool true
    defaults write com.apple.finder ShowStatusBar -bool true

    # Faster key repeat — better for coding navigation
    defaults write NSGlobalDomain KeyRepeat -int 2
    defaults write NSGlobalDomain InitialKeyRepeat -int 15

    # Disable autocorrect (it fights code variable names)
    defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false

    # Restart Finder to apply hidden-file setting immediately
    killall Finder 2>/dev/null || true

    ok "macOS defaults applied"
}
