#!/usr/bin/env bash
# @decision: Tour is a non-interactive printed narrative — no read prompts — so it can
# safely be sourced inside setup.sh without blocking. Written at a "day one coder" level:
# explains the why of each tool, not just the what. Kept printable so the user can scroll
# back and re-read without re-running setup.

_tour_header() {
    echo ""
    echo -e "${BOLD}${CYAN}$*${RESET}"
    echo -e "${CYAN}$(printf '─%.0s' $(seq 1 50))${RESET}"
}

_tour_item() {
    local name="$1"; shift
    echo -e "  ${BOLD}${WHITE}${name}${RESET}  $*"
}

print_tour() {
    echo ""
    echo -e "${BOLD}${WHITE}╔══════════════════════════════════════════════╗${RESET}"
    echo -e "${BOLD}${WHITE}║       Your New Setup: A Quick Tour           ║${RESET}"
    echo -e "${BOLD}${WHITE}╚══════════════════════════════════════════════╝${RESET}"

    _tour_header "1. Apps Installed"
    echo ""
    echo -e "  ${BOLD}${WHITE}Security & Identity${RESET}"
    _tour_item "1Password"      "Your password manager. Save every password here — never reuse one again."
    _tour_item "Signal"         "End-to-end encrypted messaging for private conversations."
    echo ""
    echo -e "  ${BOLD}${WHITE}Browsers${RESET}"
    _tour_item "Google Chrome"  "Fast, widely compatible browser — works with most web apps out of the box."
    _tour_item "Firefox"        "Privacy-focused, open source. Great for development with excellent DevTools."
    echo ""
    echo -e "  ${BOLD}${WHITE}Communication${RESET}"
    _tour_item "Discord"        "Where developer communities live. Search for servers about whatever you're learning."
    _tour_item "Slack"          "Team communication — you'll use this at most companies."
    _tour_item "Zoom"           "Video calls and meetings."
    echo ""
    echo -e "  ${BOLD}${WHITE}Development${RESET}"
    _tour_item "VS Code"        "Your code editor. Configured with extensions, a dark theme, and the Nerd Font."
    _tour_item "iTerm2"         "A much better terminal. Split panes, clickable links, search, and profiles."
    _tour_item "Docker Desktop" "Runs containers locally — package apps so they work the same everywhere."
    _tour_item "Postman"        "Test APIs visually. Send requests, inspect responses, save collections."
    echo ""
    echo -e "  ${BOLD}${WHITE}Productivity${RESET}"
    _tour_item "Rectangle"      "Snap windows to halves, thirds, or corners with keyboard shortcuts."
    _tour_item "Raycast"        "Replaces Spotlight. Clipboard history (CMD+SHIFT+V), file search, snippets."
    echo ""
    echo -e "  ${BOLD}${WHITE}Networking${RESET}"
    _tour_item "Tailscale"      "Creates a private network between your devices — access your home machine remotely."
    echo ""
    echo -e "  ${BOLD}${WHITE}Media & Utilities${RESET}"
    _tour_item "Spotify"        "Music. Helps with the long coding sessions."
    _tour_item "The Unarchiver" "Opens zip, rar, 7z, and every other archive format."
    _tour_item "VLC"            "Plays any video or audio file, no codecs needed."

    _tour_header "2. Your Terminal"
    echo ""
    echo "  Your shell is zsh — the default on modern macOS."
    echo ""
    echo "  We added:"
    _tour_item "Starship"         "A smart prompt that shows your folder, git branch, and language version."
    _tour_item "oh-my-zsh"        "Manages shell plugins and gives you smarter tab-completion."
    _tour_item "Autosuggestions"  "As you type, you'll see a ghost of your last matching command. Press → to accept."
    _tour_item "Syntax highlight" "Commands turn green as you type if valid, red if not found."
    echo ""
    echo "  Shortcuts you now have:"
    echo ""
    echo -e "    ${BOLD}CTRL+R${RESET}     Fuzzy search your command history"
    echo -e "    ${BOLD}CTRL+T${RESET}     Fuzzy file picker — find and paste any file path"
    echo -e "    ${BOLD}ll${RESET}         List files with sizes, dates, and icons"
    echo -e "    ${BOLD}cat file${RESET}   View a file with syntax highlighting"
    echo -e "    ${BOLD}rg pattern${RESET} Search inside files fast (better grep)"
    echo -e "    ${BOLD}tldr git${RESET}   Friendly cheat sheet for any command"
    echo -e "    ${BOLD}mkcd name${RESET}  Create a folder and enter it in one step"
    echo -e "    ${BOLD}serve${RESET}      Start a local web server in the current folder"

    _tour_header "3. Node.js"
    echo ""
    echo "  Node.js LTS was installed for you via nvm."
    echo ""
    echo -e "    ${BOLD}node --version${RESET}          # confirm it's there"
    echo -e "    ${BOLD}nvm install 20${RESET}          # install a specific version"
    echo -e "    ${BOLD}nvm use 20${RESET}              # switch to it"
    echo -e "    ${BOLD}nvm alias default 20${RESET}    # make it the default"
    echo ""
    echo "  nvm lets you switch Node versions per project — no conflicts, no sudo."

    _tour_header "4. VS Code"
    echo ""
    echo "  Extensions installed:"
    echo ""
    _tour_item "Prettier"           "Formats your code on save — no more worrying about spacing."
    _tour_item "ESLint"             "Warns you about JavaScript mistakes as you type."
    _tour_item "GitLens"            "Shows who wrote every line of code, right inside the editor."
    _tour_item "ErrorLens"          "Displays errors inline — no more hunting for squiggly lines."
    _tour_item "Material Icons"     "Icons for every file type in the sidebar."
    _tour_item "Indent Rainbow"     "Colors each indentation level — essential for Python and YAML."
    _tour_item "Spell Checker"      "Catches typos in comments and strings."
    _tour_item "Python / Go / Rust" "Language support for autocomplete, type hints, and error checking."
    echo ""
    echo "  Useful VS Code commands:"
    echo ""
    echo -e "    ${BOLD}code .${RESET}          Open VS Code in the current folder"
    echo -e "    ${BOLD}code myfile.js${RESET}  Open a specific file"
    echo -e "    ${BOLD}CMD+P${RESET}           Quick file search inside a project"
    echo -e "    ${BOLD}CMD+SHIFT+P${RESET}     Command palette — search for any VS Code action"
    echo -e "    ${BOLD}CMD+\`${RESET}           Open the integrated terminal"

    _tour_header "5. Git: Version Control"
    echo ""
    echo "  Git tracks every change you make so you can undo mistakes,"
    echo "  collaborate with others, and see the history of any file."
    echo ""
    echo "  Core concepts:"
    echo ""
    echo -e "    ${BOLD}repository (repo)${RESET}  A folder git is tracking. Created with: git init"
    echo -e "    ${BOLD}commit${RESET}             A saved snapshot of your changes. Like a game checkpoint."
    echo -e "    ${BOLD}branch${RESET}             A parallel version of your code. Experiment safely."
    echo -e "    ${BOLD}remote${RESET}             A copy of your repo on GitHub. Backup + sharing."
    echo ""
    echo "  Daily workflow:"
    echo ""
    echo -e "    ${BOLD}git init${RESET}            Start tracking a folder with git"
    echo -e "    ${BOLD}git status${RESET}          See what changed (alias: gs)"
    echo -e "    ${BOLD}git add .${RESET}           Stage all changes (alias: ga .)"
    echo -e "    ${BOLD}git commit -m 'msg'${RESET} Save a snapshot (alias: gc 'msg')"
    echo -e "    ${BOLD}git log${RESET}             See your commit history (alias: gl)"
    echo -e "    ${BOLD}git push${RESET}            Upload commits to GitHub (alias: gp)"
    echo -e "    ${BOLD}git pull${RESET}            Download latest changes from GitHub"
    echo ""
    echo -e "  ${DIM}Rule of thumb: commit early, commit often. Each commit should do one thing.${RESET}"

    _tour_header "6. Next Steps"
    echo ""
    echo "  A few things to do after setup:"
    echo ""
    echo -e "  ${BOLD}a) Sign into GitHub in VS Code${RESET}"
    echo "     Click the account icon at the bottom-left of VS Code."
    echo "     This syncs settings and lets GitLens access private repos."
    echo ""
    echo -e "  ${BOLD}b) Restart iTerm2${RESET}"
    echo "     Close this window and open iTerm2 to see your new prompt."
    echo ""
    echo -e "  ${BOLD}c) Set up Rectangle shortcuts${RESET}"
    echo "     Open Rectangle from Applications — it runs in the menu bar."
    echo "     Try CMD+OPT+← to snap a window to the left half."
    echo ""
    echo -e "  ${DIM}Tip: When you want to learn about any command, run: tldr <commandname>${RESET}"
    echo ""
}

print_tour
